.SUFFIXES: .java .class

.java.class:
       javac %s

all:  IDataElementViewer.class DataElementLabelProvider.class TestContentProvider.class TreeContentProvider.class TableContentProvider.class ViewMenu.class ViewFilter.class DataElementSorter.class ExtendedTreeViewer.class ExtendedTableViewer.class ObjectTreeSample.class ObjectSelectionChangedListener.class ObjectWindow.class TestUI.class ViewToolBar.class OldEditor.class EditorCanvas.class

clean:
	rm *.class

