.SUFFIXES: .java .class

.java.class:
       javac %s

all:  SearchDialog.class DataElementFileDialog.class DataElementFileTransferDialog.class DictionarySearchDialog.class FindFileDialog.class 

clean:
	rm *.class

