all: CppSourceViewerConfiguration.class CppCompletionProcessor.class

CppSourceViewerConfiguration.class: CppSourceViewerConfiguration.java
	javac $(FLAGS) CppSourceViewerConfiguration.java

CppCompletionProcessor.class: CppCompletionProcessor.java
	javac $(FLAGS) CppCompletionProcessor.java