#Copyright (C) 2000, 2001 International Business Machines Corporation and others. All Rights Reserved.
all: CppLoadLauncher.class

CppLoadLauncher.class: CppLoadLauncher.java
	javac CppLoadLauncher.java

clean:
	del *.class

