#Copyright (C) 2000, 2001 International Business Machines Corporation and others. All Rights Reserved.
all: CppLauncher.class

CppLauncher.class: CppLauncher.java
	javac CppLauncher.java

clean:
	del *.class

