.SUFFIXES: .java .class

.java.class:
       javac %s

all:  SelectFileAction.class HostConnectAction.class FileTransferAction.class TransferFiles.class ITransferListener.class SearchDictionaryAction.class FindFileAction.class QuickConnectAction.class

clean:
	rm *.class

