#! /bin/sh
#This is the cron job that updates our download page.  It currently runs on machine turnham
#at 5:00 a.m.

#Path to the cdt-home
rootDir=/home/turnham/cdtweb
#Change the next 2 lines when we change the build that CDT is being built with
eclipseVersion=F2
eclipseLink=http://download.eclipse.org/downloads/drops/S-F2-200206020843/index.php
netrc=$HOME/.netrc
theDate=`date +%Y%m%d`
theDate2=`date +%Y/%m/%d`

#Goto the CVS downloads directory and do a CVS update (so that the subsequent commit won't complain)
cd $rootDir/cdt-home/downloads
cvs update

#Remove any existing .zip files or errors file
rm -f *.zip
rm -f errors

#Get the Errors File and the driver from goose
rm $netrc
touch $netrc
chmod 600 $netrc
echo "machine goose login anonymous password turnham@ca.ibm.com" >>$netrc
echo "macdef init" >>$netrc
echo "image" >>$netrc
echo "prompt" >>$netrc
echo "cd pub/$eclipseVersion/latest" >>$netrc
echo "get errors" >>$netrc
echo "bin" >>$netrc
echo "mget cdt-eclipse-R2-$theDate.zip" >>$netrc
echo "bye" >>$netrc
echo "close" >>$netrc
echo "" >>$netrc
ftp goose
rm $netrc

#Send mail if errors file is large, also set the status to PASS or FAIL and update mainLatestNightly.html if the build was successful
theSize=`ls -l errors | awk '{print $5}'`
if [ $theSize -gt 900 ] ;
 then
  theStatus=FAIL
  cat $rootDir/cdt-home/downloads/ErrorsMessage.txt errors | mail -s "POSSIBLE ERRORS IN CDT NIGHTLY BUILD" turnham@ca.ibm.com weisz@ca.ibm.com chanskw@ca.ibm.com dmcknigh@ca.ibm.com
 else
  theStatus=PASS
  mln=mainLatestNightly.html
  echo "<tr>" > $mln
  echo "<td><a href=\"http://download.eclipse.org/eclipse/downloads/build_types.html\">Nightly</a></td>" >> $mln
  echo "<td>$theDate2</td>" >> $mln
  echo "<td><a href=\"$eclipseLink\">$eclipseVersion</a></td>" >> $mln
  echo "<td><a href=\"http://download.eclipse.org/tools/cdt/downloads/nightly/$theDate/cdt-eclipse-R2-$theDate.zip\">cdt-eclipse-R2-$theDate.zip</a></td>" >> $mln
  echo "</tr>" >> $mln
fi

#Add the nightly build to mainNightly.html
mn=mainNightly.new
echo "<tr>" >> $mn
echo "<td>$theDate2</td>" >> $mn
echo "<td><a href=\"http://download.eclipse.org/tools/cdt/downloads/nightly/$theDate/errors\">Error Log</a>" >> $mn
echo " <img alt=\"\" src=\"http://dev.eclipse.org/viewcvs/index.cgi/%7Echeckout%7E/cdt-home/downloads/$theStatus.gif?cvsroot=Tools_Project\"></td>" >> $mn
echo "<td><a href=\"$eclipseLink\">$eclipseVersion</a></td>" >> $mn
echo "<td><a href=\"http://download.eclipse.org/tools/cdt/downloads/nightly/$theDate/cdt-eclipse-R2-$theDate.zip\">cdt-eclipse-R2-$theDate.zip</a></td>" >> $mn
echo "</tr>" >> $mn
mv mainNightly.html mainNightly.old
cat $mn mainNightly.old > mainNightly.html
rm -f $mn


#Now just put the pieces together
cat mainTop.html            > main.html
cat mainLatestNightly.html >> main.html
cat mainRelease.html       >> main.html
cat mainStable.html        >> main.html
cat mainNightly.html       >> main.html

#ftp the zip and error file over to the download site

#What you thought I would put my password in this file? ;-)
ftpPassword=`cat ftpPassword`

touch $netrc
chmod 600 $netrc
echo "machine download.eclipse.org login turnham password $ftpPassword" >>$netrc
echo "macdef init" >>$netrc
echo "image" >>$netrc
echo "prompt" >>$netrc
echo "cd nightly" >>$netrc
echo "mkdir $theDate" >>$netrc
echo "cd $theDate" >>$netrc
echo "put cdt-eclipse-R2-$theDate.zip" >>$netrc 
echo "put errors"  >>$netrc
echo "bye" >>$netrc 
echo "close" >>$netrc
echo "" >>$netrc
ftp download.eclipse.org
rm $netrc
rm errors
rm cdt-eclipse-R2-$theDate.zip

#Commit changes
cvs commit -m 'Automated update' main.html mainNightly.html mainLatestNightly.html
echo "All done"
echo `date`
