all: PlatformVCMProvider.class Repository.class DataStoreLocation.class CreateProjectAction.class RemoteProjectAdapter.class RepositoryDescription.class

CreateProjectAction.class: CreateProjectAction.java
	javac CreateProjectAction.java

PlatformVCMProvider.class: PlatformVCMProvider.java
	javac PlatformVCMProvider.java

Repository.class: Repository.java
	javac Repository.java

RepositoryDescription.class: RepositoryDescription.java
	javac RepositoryDescription.java

DataStoreAdapter.class: DataStoreAdapter.java
	javac DataStoreAdapter.java

DataStoreLocation.class: DataStoreLocation.java
	javac DataStoreLocation.java

RemoteProjectAdapter.class: RemoteProjectAdapter.java
	javac RemoteProjectAdapter.java
