/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package org.eclipse.cdt.cpp.miners.parser.grammar;

public interface ParserConstants {

  int EOF = 0;
  int OPENCURLY = 25;
  int CLOSECURLY = 26;
  int OPENSQUARE = 27;
  int CLOSESQUARE = 28;
  int OPENPAREN = 29;
  int CLOSEPAREN = 30;
  int SCOPE = 31;
  int COLON = 32;
  int SEMICOLON = 33;
  int COMMA = 34;
  int QUESTIONMARK = 35;
  int ELLIPSIS = 36;
  int ASSIGNEQUAL = 37;
  int TIMESEQUAL = 38;
  int DIVIDEEQUAL = 39;
  int MODEQUAL = 40;
  int PLUSEQUAL = 41;
  int MINUSEQUAL = 42;
  int SHIFTLEFTEQUAL = 43;
  int SHIFTRIGHTEQUAL = 44;
  int BITWISEANDEQUAL = 45;
  int BITWISEXOREQUAL = 46;
  int BITWISEOREQUAL = 47;
  int OR = 48;
  int AND = 49;
  int BITWISEOR = 50;
  int BITWISEXOR = 51;
  int AMPERSAND = 52;
  int EQUAL = 53;
  int NOTEQUAL = 54;
  int LESSTHAN = 55;
  int GREATERTHAN = 56;
  int LESSTHANOREQ = 57;
  int GREATERTHANOREQ = 58;
  int SHIFTLEFT = 59;
  int SHIFTRIGHT = 60;
  int PLUS = 61;
  int MINUS = 62;
  int STAR = 63;
  int DIVIDE = 64;
  int MOD = 65;
  int PLUSPLUS = 66;
  int MINUSMINUS = 67;
  int TILDE = 68;
  int NOT = 69;
  int DOT = 70;
  int POINTERTO = 71;
  int DOTSTAR = 72;
  int ARROWSTAR = 73;
  int ASM = 74;
  int AUTO = 75;
  int BREAK = 76;
  int BOOL = 77;
  int CASE = 78;
  int CATCH = 79;
  int CHAR = 80;
  int CLASS = 81;
  int CONST = 82;
  int CONST_CAST = 83;
  int CONTINUE = 84;
  int _DEFAULT = 85;
  int DELETE = 86;
  int DO = 87;
  int DOUBLE = 88;
  int DYNAMIC_CAST = 89;
  int ELSE = 90;
  int ENUM = 91;
  int EXPLICIT = 92;
  int EXPORT = 93;
  int EXTERN = 94;
  int FINALLY = 95;
  int FLOAT = 96;
  int FOR = 97;
  int FRIEND = 98;
  int GOTO = 99;
  int IF = 100;
  int INLINE = 101;
  int INT = 102;
  int LONG = 103;
  int MUTABLE = 104;
  int NAMESPACE = 105;
  int NEW = 106;
  int OPERATOR = 107;
  int PRIVATE = 108;
  int PROTECTED = 109;
  int PUBLIC = 110;
  int REGISTER = 111;
  int REINTERPET_CAST = 112;
  int RETURN = 113;
  int SHORT = 114;
  int SIGNED = 115;
  int SIZEOF = 116;
  int STATIC = 117;
  int STATIC_CAST = 118;
  int STRUCT = 119;
  int SWITCH = 120;
  int TEMPLATE = 121;
  int THIS = 122;
  int THROW = 123;
  int TRY = 124;
  int TYPEDEF = 125;
  int TYPEID = 126;
  int TYPENAME = 127;
  int UNION = 128;
  int UNSIGNED = 129;
  int USING = 130;
  int VIRTUAL = 131;
  int VOID = 132;
  int VOLATILE = 133;
  int WCHAR_T = 134;
  int WHILE = 135;
  int OCTALINT = 136;
  int OCTALLONG = 137;
  int UNSIGNED_OCTALINT = 138;
  int UNSIGNED_OCTALLONG = 139;
  int DECIMALINT = 140;
  int DECIMALLONG = 141;
  int UNSIGNED_DECIMALINT = 142;
  int UNSIGNED_DECIMALLONG = 143;
  int HEXADECIMALINT = 144;
  int HEXADECIMALLONG = 145;
  int UNSIGNED_HEXADECIMALINT = 146;
  int UNSIGNED_HEXADECIMALLONG = 147;
  int FLOATONE = 148;
  int FLOATTWO = 149;
  int CHARACTER = 150;
  int STRING = 151;
  int ID = 152;

  int DEFAULT = 0;
  int LINE_NUMBER = 1;
  int LINE_DIRECTIVE_SPACES = 2;
  int LINE_DIRECTIVE_FILE = 3;
  int LINE_DIRECTIVE_END = 4;
  int AFTER_LINE_DIRECTIVE = 5;
  int IN_DEFINE = 6;
  int IN_LINE_COMMENT = 7;
  int IN_COMMENT = 8;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\\\\\n\"",
    "\"##\"",
    "\"\\u001a\"",
    "\"//\"",
    "\"/*\"",
    "\"#define \"",
    "<token of kind 11>",
    "<token of kind 12>",
    "<token of kind 13>",
    "<token of kind 14>",
    "<token of kind 15>",
    "\"\\n\"",
    "<token of kind 17>",
    "<token of kind 18>",
    "\"\\n\"",
    "<token of kind 20>",
    "\"\\n\"",
    "<token of kind 22>",
    "\"*/\"",
    "<token of kind 24>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"asm\"",
    "\"auto\"",
    "\"break\"",
    "\"bool\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"const_cast\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"double\"",
    "\"dynamic_cast\"",
    "\"else\"",
    "\"enum\"",
    "\"explicit\"",
    "\"export\"",
    "\"extern\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"goto\"",
    "\"if\"",
    "\"inline\"",
    "\"int\"",
    "\"long\"",
    "\"mutable\"",
    "\"namespace\"",
    "\"new\"",
    "\"operator\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"register\"",
    "\"reinterpret_cast\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"static_cast\"",
    "\"struct\"",
    "\"switch\"",
    "\"template\"",
    "\"this\"",
    "\"throw\"",
    "\"try\"",
    "\"typedef\"",
    "\"typeid\"",
    "\"typename\"",
    "\"union\"",
    "\"unsigned\"",
    "\"using\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"wchar_t\"",
    "\"while\"",
    "<OCTALINT>",
    "<OCTALLONG>",
    "<UNSIGNED_OCTALINT>",
    "<UNSIGNED_OCTALLONG>",
    "<DECIMALINT>",
    "<DECIMALLONG>",
    "<UNSIGNED_DECIMALINT>",
    "<UNSIGNED_DECIMALLONG>",
    "<HEXADECIMALINT>",
    "<HEXADECIMALLONG>",
    "<UNSIGNED_HEXADECIMALINT>",
    "<UNSIGNED_HEXADECIMALLONG>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
    "<ID>",
    "\"\\\"\"",
  };

}
