/* Generated By:JavaCC: Do not edit this line. ArgumentsParserConstants.java */
package org.eclipse.cdt.debug.gdbPicl.parser;

public interface ArgumentsParserConstants {

  int EOF = 0;
  int QOUTED_STRING = 5;
  int STRING = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<QOUTED_STRING>",
    "<STRING>",
  };

}
