.SUFFIXES: .java .class

.java.class:
       javac %s

all: ActionBuildTarget.class ActionNewTarget.class ActionRemoveAllTarget.class ActionRemoveTarget.class \
 ActionTarget.class BaseElement.class BrowseCellEditor.class BrowsePropertyDescriptor.class \
 CppPluginImages.class CreateTargetAction.class IPropertyDescriptor.class IPropertySheetEntry.class \
 IPropertySheetEntryListener.class IPropertySheetPage.class IPropertySource.class IPropertySourceProvider.class \
 IResourcePropertyConstants.class NavigatorSelection.class NewTargetGroup.class NewTargetWizard.class \
 NewWizardTargetMainPage.class PropertyDescriptor.class PropertySheetCategory.class ResourcePropertySource.class \
 RootElement.class StandardPropertiesAdapterFactory.class TargetElement.class Targets.class \
 TargetSelectionDialog.class TargetSelectionGroup.class TargetsEntry.class TargetsPage.class TargetsStore.class \
 TargetsViewer.class TextPropertyDescriptor.class

clean:
	rm *.class
