/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package com.ibm.linux.help.util.lucene.queryParser;

public interface QueryParserConstants {

  int EOF = 0;
  int _ALPHA_CHAR = 1;
  int _NUM_CHAR = 2;
  int _ALPHANUM_CHAR = 3;
  int _IDENTIFIER_CHAR = 4;
  int _IDENTIFIER = 5;
  int _NEWLINE = 6;
  int _WHITESPACE = 7;
  int _QCHAR = 8;
  int _RESTOFLINE = 9;
  int AND = 10;
  int OR = 11;
  int NOT = 12;
  int PLUS = 13;
  int MINUS = 14;
  int LPAREN = 15;
  int RPAREN = 16;
  int COLON = 17;
  int CARAT = 18;
  int STAR = 19;
  int QUOTED = 20;
  int NUMBER = 21;
  int TERM = 22;
  int FUZZY = 23;
  int WILDTERM = 24;
  int RANGEIN = 25;
  int RANGEEX = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<_ALPHA_CHAR>",
    "<_NUM_CHAR>",
    "<_ALPHANUM_CHAR>",
    "<_IDENTIFIER_CHAR>",
    "<_IDENTIFIER>",
    "<_NEWLINE>",
    "<_WHITESPACE>",
    "<_QCHAR>",
    "<_RESTOFLINE>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"+\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"^\"",
    "\"*\"",
    "<QUOTED>",
    "<NUMBER>",
    "<TERM>",
    "\"~\"",
    "<WILDTERM>",
    "<RANGEIN>",
    "<RANGEEX>",
    "<token of kind 27>",
  };

}
