.SUFFIXES: .java .class

.java.class:
       javac %s

all:   CharStringPointer.class            \
       MalformedPatternException.class    \
       MatchResult.class                  \
       OpCode.class                       \
       Pattern.class                      \
       PatternCompiler.class              \
       PatternMatcher.class               \
       PatternMatcherInput.class          \
       Perl5Compiler.class                \
       Perl5Debug.class                   \
       Perl5Matcher.class                 \
       Perl5MatchResult.class             \
       Perl5Pattern.class                 \
       Perl5Repetition.class              \
       Perl5Substitution.class            \
       StringSubstitution.class           \
       Substitution.class                 \
       Util.class

clean:
	rm *.class
