.SUFFIXES: .java .class

.java.class:
       javac %s

all: DE.class PM.class DataElement.class DataStore.class DataStoreAttributes.class \
	Handler.class UpdateHandler.class CommandHandler.class

clean:
	rm *.class
