all: CppEditorAction.class CppEditorContextContributor.class

CppEditorAction.class: CppEditorAction.java
	javac $(FLAGS) CppEditorAction.java

CppEditorContextContributor.class: CppEditorContextContributor.java
	javac $(FLAGS) CppEditorContextContributor.java