# Copyright (C) 2000, 2001 International Business Machines Corporation and others. All Rights Reserved.
SHELL=sh
include E:/eclipse/eclipse/plugins/com.ibm.dstore.miners/com/ibm/dstore/miners/setenv.mk
include E:/eclipse/eclipse/plugins/com.ibm.dstore.core/com/ibm/dstore/core/build/rules.mk
