.SUFFIXES: .java .class

.java.class:
       javac %s

all:  ResourceElement.class FileResourceElement.class FolderResourceElement.class ProjectResourceElement.class IDataElementContainer.class ElementMarker.class

clean:
	rm *.class

