
all: ModelInterface.class DataElementAdapter.class DataElementAdapterFactory.class SearchLabelProvider.class \
	CppProjectNotifier.class CppProjectEvent.class ICppProjectListener.class

ICppProjectListener.class: ICppProjectListener.java
	javac ICppProjectListener.java

CppProjectEvent.class: CppProjectEvent.java
	javac CppProjectEvent.java

CppProjectNotifier.class: CppProjectNotifier.java
	javac CppProjectNotifier.java

ModelInterface.class: ModelInterface.java
	javac ModelInterface.java

DataElementAdapter.class: DataElementAdapter.java
	javac DataElementAdapter.java

DataElementAdapterFactory.class: DataElementAdapterFactory.java
	javac DataElementAdapterFactory.java

SearchLabelProvider.class: SearchLabelProvider.java
	javac SearchLabelProvider.java

