.SUFFIXES: .java .class

.java.class:
       javac %s

all: CppNewProjectResourceWizard.class CppWizardNewProjectCreationPage.class ProjectInfoWizardPage.class ParsePathWorkbookPage.class ParseQualityWorkbookPage.class BuildInvocationWorkbookPage.class BuildInvocationEntry.class EnvironmentWorkbookPage.class ParseWizardPage.class

clean:
	rm *.class

