.SUFFIXES: .java .class

.java.class:
       javac %s

all: RemoteOperation.class CommandAction.class OpenSectionAction.class CloseSectionAction.class ImportAction.class ExportAction.class ModifyAction.class UICommandAction.class CustomAction.class ZoomInAction.class OpenEditorAction.class OpenPerspectiveAction.class

clean:
	rm *.class
