package com.ibm.debug.launch;

////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2001, 2002 International Business Machines Corporation. All rights reserved.
// This program and the accompanying materials are made available under the terms of
// the Common Public License which accompanies this distribution.
//
// com/ibm/debug/launch/PICLDaemonInfo.java, eclipse, eclipse-dev, 20011128
// Version 1.3 (last modified 11/28/01 16:00:13)
////////////////////////////////////////////////////////////////////////////////

/**
 * Note: This class/interface is part of an interim API that is still under
 * development and expected to change significantly before reaching stability.
 * It is being made available at this early stage to solicit feedback from
 * pioneering adopters on the understanding that any code that uses this API
 * will almost certainly be broken (repeatedly) as the API evolves.
 */

/**
 * This class is used to provide launch or startup information for a debug
 * session.  This class is abstract and cannot be instantiated.  One of its
 * subclasses (e.g. PICLAttachInfo, PICLLoadInfo) should be instantiated
 * instead.  This class is not intended to be subclassed outside of this
 * plugin.
 */


public class PICLDaemonInfo {

    private int fKey;
    private int fPort;

    /**
     * Construct a PICLDaemonInfo.
     * @param key The unique key generated by the daemon for this launch.
     * @param port The port that the daemon is listening on.
     */
    public PICLDaemonInfo(int key, int port) {
        fKey = key;
        fPort = port;
    }

    /**
     * Get the key.
     * @returns The unique key that was generated by the daemon.
     */
    public int getKey() {
        return fKey;
    }

    /**
     * Get the port.
     * @returns The port that the daemon is listening on.
     */
    public int getPort() {
        return fPort;
    }
}
