.SUFFIXES: .java .class

.java.class:
       javac %s

all: CppBuilder.class BuildPropertyPage.class ParsePathControl.class ParseQualityPropertyPage.class ParsePathPropertyPage.class EnvironmentPropertyPage.class RemotePropertyPage.class

clean:
	rm *.class

