all: OutputPattern.class CommandPattern.class Patterns.class

OutputPattern.class: OutputPattern.java
	javac OutputPattern.java

CommandPattern.class: CommandPattern.java
	javac CommandPattern.java

Patterns.class: Patterns.java
	javac Patterns.java

