# Copyright (C) 2000, 2001 International Business Machines Corporation and others. All Rights Reserved.
SHELL=sh
include E:/eclipse/eclipse/plugins/com.ibm.cpp.ui/com/ibm/cpp/ui/setenv.mk
include E:/eclipse/eclipse/plugins/com.ibm.dstore.core/com/ibm/dstore/core/build/rules.mk
