.SUFFIXES: .java .class

.java.class:
       javac %s

all:  HostsViewPart.class HostsPerspective.class OutputViewer.class OutputViewPart.class CommandViewPart.class CommandViewer.class HostsDetailsViewPart.class

clean:
	rm *.class

