.SUFFIXES: .java .class

.java.class:
       javac %s

all: ClientAttributes.class ClientConnection.class ClientReceiver.class ClientUpdateHandler.class ClientCommandHandler.class ConnectionStatus.class

clean:
	rm *.class
