
all: ModifyDialog.class CommandDialog.class ConnectDialog.class LoginDialog.class

LoginDialog.class: LoginDialog.java
	javac LoginDialog.java

ConnectDialog.class: ConnectDialog.java
	javac ConnectDialog.java

CommandDialog.class: CommandDialog.java
	javac CommandDialog.java

ModifyDialog.class: ModifyDialog.java
	javac ModifyDialog.java

clean:
	rm *.class
