all: CppActionDelegateBuild.class CppActionDelegateDesignate.class CppActionDelegateUnDesignate.class CppActionDelegateFolderBuild.class ParseAction.class OpenPerspectiveAction.class RefreshNavigatorAction.class SaveAction.class ClearAction.class OpenEditorAction.class AbstractSourceSyncher.class SourceSyncher.class SourceReleaser.class SourceExtractor.class SynchronizeFiles.class ReleaseFiles.class ExtractFiles.class MergeFiles.class AddStatementBreakpoint.class AddFunctionBreakpoint.class AddClassBreakpoint.class

AddClassBreakpoint.class: AddClassBreakpoint.java
	javac $(FLAGS) AddClassBreakpoint.java

AddStatementBreakpoint.class: AddStatementBreakpoint.java
	javac $(FLAGS) AddStatementBreakpoint.java

AddFunctionBreakpoint.class: AddFunctionBreakpoint.java
	javac $(FLAGS) AddFunctionBreakpoint.java

SourceReleaser.class: SourceReleaser.java
	javac $(FLAGS) SourceReleaser.java

SourceExtractor.class: SourceExtractor.java
	javac $(FLAGS) SourceExtractor.java

SourceSyncher.class: SourceSyncher.java
	javac $(FLAGS) SourceSyncher.java	

AbstractSourceSyncher.class: AbstractSourceSyncher.java
	javac $(FLAGS) AbstractSourceSyncher.java	

SynchronizeFiles.class: SynchronizeFiles.java
	javac $(FLAGS) SynchronizeFiles.java	

ReleaseFiles.class: ReleaseFiles.java
	javac $(FLAGS) ReleaseFiles.java	

ExtractFiles.class: ExtractFiles.java
	javac $(FLAGS) ExtractFiles.java	

MergeFiles.class: MergeFiles.java
	javac $(FLAGS) MergeFiles.java	

RefreshNavigatorAction.class: RefreshNavigatorAction.java
	javac $(FLAGS) RefreshNavigatorAction.java

OpenEditorAction.class: OpenEditorAction.java
	javac $(FLAGS) OpenEditorAction.java

OpenPerspectiveAction.class: OpenPerspectiveAction.java
	javac $(FLAGS) OpenPerspectiveAction.java

CppActionDelegateFolderBuild.class: CppActionDelegateFolderBuild.java
	javac $(FLAGS) CppActionDelegateFolderBuild.java

CppActionDelegateUnDesignate.class: CppActionDelegateUnDesignate.java
	javac $(FLAGS) CppActionDelegateUnDesignate.java

CppActionDelegateDesignate.class: CppActionDelegateDesignate.java
	javac $(FLAGS) CppActionDelegateDesignate.java

CppActionDelegateBuild.class: CppActionDelegateBuild.java
	javac $(FLAGS) CppActionDelegateBuild.java

ParseAction.class: ParseAction.java
	javac $(FLAGS) ParseAction.java

SaveAction.class: SaveAction.java
	javac $(FLAGS) SaveAction.java

ClearAction.class: ClearAction.java
	javac $(FLAGS) ClearAction.java

clean:
	rm *.class
