.SUFFIXES: .java .class

.java.class:
       javac %s

all: CppActionDelegateBuild.class CppActionDelegateDesignate.class CppActionDelegateUnDesignate.class CppActionDelegateFolderBuild.class ParseAction.class OpenPerspectiveAction.class RefreshNavigatorAction.class SaveAction.class ClearAction.class OpenEditorAction.class AbstractSourceSyncher.class SourceSyncher.class SourceReleaser.class SourceExtractor.class SynchronizeFiles.class ReleaseFiles.class ExtractFiles.class MergeFiles.class AddStatementBreakpoint.class AddFunctionBreakpoint.class AddClassBreakpoint.class FindObjectAction.class

clean:
	rm *.class
