# Copyright (C) 2000, 2001 International Business Machines Corporation and others. All Rights Reserved.
SHELL=sh
include /home/enriquev/R1000/eclipse/plugins/com.ibm.linux.help/com/ibm/linux/help/setenv.mk
include /home/enriquev/R1000/eclipse/plugins/com.ibm.dstore.core/com/ibm/dstore/core/build/rules.mk
